import { useEffect, useMemo, useState } from 'react'
import {
  Activity, ArrowDownRight, ArrowUpRight, Bell, CalendarDays, Check, ChevronRight,
  CircleDollarSign, ClipboardList, Download, LayoutDashboard, LogOut, Menu, Plus,
  Search, Settings, ShoppingBag, SlidersHorizontal, Sparkles, Store, TrendingUp,
  UserRound, Wallet, X, BarChart3
} from 'lucide-react'
import {
  Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer,
  Tooltip, XAxis, YAxis
} from 'recharts'

type Page = 'dashboard' | 'planner' | 'reverse-planner' | 'repayment-dna' | 'loans' | 'repayments' | 'sales' | 'calendar' | 'reports' | 'notifications' | 'profile' | 'admin'
type LoanStatus = 'active' | 'completed' | 'overdue'
type PaymentMethod = 'Cash' | 'UPI' | 'Bank Transfer' | 'Card' | 'Other'
type Loan = { id: string; loanId: string; lender: string; principal: number; interest: number; total: number; start: string; due: string; frequency: string; duration: number; status: LoanStatus; notes: string }
type Repayment = { id: string; loanId: string; amount: number; date: string; method: PaymentMethod; reference: string; notes: string }
type Sale = { id: string; date: string; category: string; amount: number; customers: number; method: PaymentMethod; expenses: number; notes: string }
type Notification = { id: string; title: string; message: string; type: 'success' | 'warning' | 'info'; read: boolean; date: string }
type Data = { loans: Loan[]; repayments: Repayment[]; sales: Sale[]; notifications: Notification[] }

const today = new Date()
const APP_BUILD = '2026-09-24-no-digital-twin'
const iso = (date: Date) => date.toISOString().slice(0, 10)
const dayOffset = (amount: number) => { const d = new Date(); d.setDate(d.getDate() + amount); return iso(d) }
const demoData: Data = {
  loans: [
    { id: 'l1', loanId: 'LN-001', lender: 'Jan Dhan Microfinance', principal: 50000, interest: 10, total: 55000, start: dayOffset(-82), due: dayOffset(7), frequency: 'Monthly', duration: 12, status: 'active', notes: 'Working capital for fresh produce stock.' },
    { id: 'l2', loanId: 'LN-002', lender: 'Sahyog Capital', principal: 25000, interest: 8, total: 27000, start: dayOffset(-140), due: dayOffset(-3), frequency: 'Weekly', duration: 24, status: 'overdue', notes: 'Market stall equipment.' }
  ],
  repayments: [
    { id: 'r1', loanId: 'l1', amount: 15000, date: dayOffset(-54), method: 'UPI', reference: 'UPI-38492', notes: '' },
    { id: 'r2', loanId: 'l1', amount: 15000, date: dayOffset(-24), method: 'Bank Transfer', reference: 'NEFT-1120', notes: '' },
    { id: 'r3', loanId: 'l2', amount: 18000, date: dayOffset(-28), method: 'Cash', reference: '', notes: '' }
  ],
  sales: [-1, -2, -3, -4, -5, -6, 0].map((offset, i) => ({ id: `s${i}`, date: dayOffset(offset), category: i % 2 ? 'Vegetables' : 'Fruits', amount: [104.8387, 99.5238, 110, 96.6038, 95.7895, 99.5652, 97.25][i], customers: [31, 42, 26, 53, 38, 46, 40][i], method: i % 3 ? 'UPI' : 'Cash', expenses: [800, 920, 620, 1100, 740, 950, 780][i], notes: '' })),
  notifications: [
    { id: 'n1', title: 'Upcoming repayment', message: '₹4,583 repayment for LN-001 is due in 7 days.', type: 'info', read: false, date: dayOffset(-1) },
    { id: 'n2', title: 'Overdue repayment', message: 'LN-002 has an overdue repayment. Review your calendar.', type: 'warning', read: false, date: dayOffset(-2) },
    { id: 'n3', title: 'Great sales day', message: 'You crossed ₹4,000 in sales yesterday.', type: 'success', read: true, date: dayOffset(-1) }
  ]
}

const money = (value: number) => `${value < 0 ? '-' : ''}₹${Math.abs(Math.round(value)).toLocaleString('en-IN')}`
const dateLabel = (date: string) => new Date(`${date}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })
const cls = (...names: (string | false | undefined)[]) => names.filter(Boolean).join(' ')
const saleTotal = (sale: Sale) => sale.amount * Math.max(0, sale.customers)
const loanInterestAmount = (loan: Loan) => Math.max(0, loan.principal * loan.interest / 100)
function remainingInterest(loan: Loan, repayments: Repayment[]) {
  const outstanding = loanOutstanding(loan, repayments)
  return loan.total > 0 ? Math.min(loanInterestAmount(loan), loanInterestAmount(loan) * outstanding / loan.total) : 0
}
function readData(): Data { try { const stored = localStorage.getItem('microloan-data'); return stored ? JSON.parse(stored) : demoData } catch { return demoData } }
function loanPaid(loan: Loan, repayments: Repayment[]) { return repayments.filter(r => r.loanId === loan.id).reduce((sum, r) => sum + r.amount, 0) }
function loanOutstanding(loan: Loan, repayments: Repayment[]) { return Math.max(0, loan.total - loanPaid(loan, repayments)) }
function loanProgress(loan: Loan, repayments: Repayment[]) { return Math.min(100, Math.round((loanPaid(loan, repayments) / loan.total) * 100)) }
function scheduledRepayment(loan: Loan) {
  const duration = Math.max(1, loan.duration || 1)
  const periods = loan.frequency === 'Daily' ? duration * 30 : loan.frequency === 'Weekly' ? duration * 52 / 12 : duration
  return loan.total / periods
}
function effectiveLoanStatus(loan: Loan, repayments: Repayment[]): LoanStatus {
  if (loanOutstanding(loan, repayments) === 0) return 'completed'
  if (loan.status === 'overdue' || loan.due < iso(today)) return 'overdue'
  return 'active'
}

const navItems: { id: Page; label: string; icon: typeof LayoutDashboard }[] = [
  { id: 'dashboard', label: 'Overview', icon: LayoutDashboard }, { id: 'planner', label: 'Smart planner', icon: Sparkles }, { id: 'reverse-planner', label: 'Reverse loan planner', icon: TrendingUp }, { id: 'repayment-dna', label: 'Repayment DNA', icon: CircleDollarSign }, { id: 'loans', label: 'Loans', icon: Wallet },
  { id: 'repayments', label: 'Repayments', icon: ClipboardList }, { id: 'sales', label: 'Sales', icon: ShoppingBag },
  { id: 'calendar', label: 'Calendar', icon: CalendarDays }, { id: 'reports', label: 'Reports', icon: BarChart3 }
]

export default function App() {
  const [showIntro, setShowIntro] = useState(() => localStorage.getItem('microloan-intro-seen') !== 'true')
  const [data, setData] = useState<Data>(readData)
  const [page, setPage] = useState<Page>('dashboard')
  const [sidebar, setSidebar] = useState(false)
  const [modal, setModal] = useState<'loan' | 'repayment' | 'sale' | null>(null)
  const [search, setSearch] = useState('')
  const [toast, setToast] = useState('')
  const [profile, setProfile] = useState({ name: 'Rahul Sharma', business: 'Rahul Fresh Fruits', type: 'Fruits & Vegetables', phone: '+91 98765 43210', email: 'rahul@example.com', location: 'Pune, Maharashtra' })
  useEffect(() => { localStorage.setItem('microloan-data', JSON.stringify(data)) }, [data])
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(''), 2800); return () => clearTimeout(t) }, [toast])
  const add = (key: 'loans' | 'repayments' | 'sales' | 'notifications', item: never) => setData(d => ({ ...d, [key]: [...d[key], item] }))
  const updateData = (next: Data) => setData(next)
  const unread = data.notifications.filter(n => !n.read).length
  const titles: Partial<Record<Page, string>> = { dashboard: 'Good morning, Rahul', planner: 'Smart Repayment Planner', 'reverse-planner': 'Reverse Loan Planner', 'repayment-dna': 'Repayment DNA' }
  const title = titles[page] ?? page[0].toUpperCase() + page.slice(1)
  if (showIntro) return <IntroPage onEnter={() => { localStorage.setItem('microloan-intro-seen', 'true'); setShowIntro(false) }} />
  return <div className="app-shell" data-build={APP_BUILD}>
    <aside className={cls('sidebar', sidebar && 'open')}>
      <div className="brand"><div className="brand-mark"><Store size={19} /></div><div><strong>MicroLoan</strong><span>TRACKER</span></div><button className="icon-btn mobile-close" onClick={() => setSidebar(false)}><X size={18} /></button></div>
      <div className="workspace-label">WORKSPACE</div>
      <nav>{navItems.map(item => <button key={item.id} className={cls('nav-item', page === item.id && 'active')} onClick={() => { setPage(item.id); setSidebar(false) }}><item.icon size={18} /><span>{item.label}</span></button>)}</nav>
      <div className="sidebar-divider" /><div className="workspace-label">ACCOUNT</div>
      <button className={cls('nav-item', page === 'notifications' && 'active')} onClick={() => { setPage('notifications'); setSidebar(false) }}><Bell size={18} /><span>Notifications</span>{unread > 0 && <b className="notification-count">{unread}</b>}</button>
      <button className={cls('nav-item', page === 'profile' && 'active')} onClick={() => { setPage('profile'); setSidebar(false) }}><UserRound size={18} /><span>Profile</span></button>
      <button className={cls('nav-item', page === 'admin' && 'active')} onClick={() => { setPage('admin'); setSidebar(false) }}><Settings size={18} /><span>Admin view</span></button>
      <div className="sidebar-bottom"><div className="user-mini"><div className="avatar">RS</div><div><strong>Rahul Sharma</strong><small>Vendor account</small></div><Settings size={16} /></div><button className="logout"><LogOut size={16} /> Sign out</button></div>
    </aside>
    {sidebar && <div className="backdrop" onClick={() => setSidebar(false)} />}
    <main className="main">
      <header className="topbar"><button className="icon-btn menu-btn" onClick={() => setSidebar(true)}><Menu size={21} /></button><div className="breadcrumb">Workspace <ChevronRight size={14} /> <span>{page === 'dashboard' ? 'Overview' : title}</span></div><div className="top-actions"><div className="search-wrap"><Search size={17} /><input aria-label="Search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search anything..." /></div><button className="icon-btn notification-button" onClick={() => setPage('notifications')}><Bell size={19} />{unread > 0 && <i />}</button><div className="avatar avatar-top">RS</div></div></header>
      <div className="content"><div className="page-heading"><div><p className="eyebrow">{page === 'dashboard' ? 'THURSDAY, SEPTEMBER 24, 2026' : 'MICROLOAN TRACKER'}</p><h1>{title}</h1>{page === 'dashboard' && <p className="subtitle">Here’s what’s happening with your business today.</p>}</div>{page === 'dashboard' && <div className="heading-actions"><button className="button button-secondary" onClick={() => setModal('sale')}><Plus size={17} /> Record sale</button><button className="button button-primary" onClick={() => setModal('loan')}><Plus size={17} /> Add loan</button></div>}</div>
        {page === 'dashboard' && <Dashboard data={data} onNavigate={setPage} />}
        {page === 'planner' && <SmartPlanner data={data} />}
        {page === 'reverse-planner' && <ReverseLoanPlanner data={data} />}
        {page === 'repayment-dna' && <RepaymentDNA data={data} />}
        {page === 'loans' && <Loans data={data} setModal={setModal} search={search} />}
        {page === 'repayments' && <Repayments data={data} setModal={setModal} />}
        {page === 'sales' && <Sales data={data} setModal={setModal} />}
        {page === 'calendar' && <Calendar data={data} />}
        {page === 'reports' && <Reports data={data} />}
        {page === 'notifications' && <Notifications data={data} updateData={updateData} />}
        {page === 'profile' && <Profile profile={profile} setProfile={setProfile} />}
        {page === 'admin' && <Admin data={data} />}
      </div>
    </main>
    {modal === 'loan' && <LoanModal close={() => setModal(null)} save={item => { add('loans', item as never); setModal(null); setToast('Loan added successfully') }} />}
    {modal === 'repayment' && <RepaymentModal data={data} close={() => setModal(null)} save={item => { add('repayments', item as never); setModal(null); setToast('Repayment recorded') }} />}
    {modal === 'sale' && <SaleModal close={() => setModal(null)} save={item => { add('sales', item as never); setModal(null); setToast('Sale recorded successfully') }} />}
    {toast && <div className="toast"><Check size={18} />{toast}</div>}
  </div>
}

function IntroPage({ onEnter }: { onEnter: () => void }) {
  return <div className="intro-page">
    <header className="intro-nav">
      <div className="intro-brand"><div className="brand-mark"><Store size={19} /></div><div><strong>MicroLoan</strong><span>TRACKER</span></div></div>
      <div className="intro-nav-actions"><span className="intro-nav-note">Simple financial tracking for small businesses</span><button className="intro-login" onClick={onEnter}>Sign in <ChevronRight size={15} /></button></div>
    </header>
    <main>
      <section className="intro-hero">
        <div className="intro-copy">
          <div className="intro-kicker"><span><Sparkles size={13} /> BUILT FOR SMALL BUSINESS</span></div>
          <h1>Make every rupee<br /><em>count.</em></h1>
          <p className="intro-lede">A simple, calm way to track loans, repayments, sales, and the financial health of your business — all in one place.</p>
          <div className="intro-cta-row"><button className="intro-cta" onClick={onEnter}>Explore your dashboard <ArrowUpRight size={17} /></button><span className="intro-cta-note"><Check size={14} /> No complicated accounting</span></div>
          <div className="intro-trust"><div className="trust-avatars"><span>RS</span><span>AM</span><span>PK</span></div><div><strong>Made for people who keep business moving</strong><small>Clear tools. Better decisions. Every day.</small></div></div>
        </div>
        <div className="intro-visual">
          <div className="visual-glow" />
          <div className="floating-card floating-card-top"><div className="floating-icon green"><TrendingUp size={15} /></div><div><small>Today's sales</small><strong>₹3,890</strong></div><ArrowUpRight size={15} className="positive" /></div>
          <div className="dashboard-preview">
            <div className="preview-top"><div className="preview-logo"><div className="brand-mark"><Store size={10} /></div><b>MicroLoan</b></div><div className="preview-user">RS</div></div>
            <div className="preview-content"><small>FINANCIAL OVERVIEW</small><h3>Good morning, Rahul</h3><div className="preview-stats"><div><span>Outstanding</span><b>₹25,000</b><i className="purple-line" /></div><div><span>Total repaid</span><b>₹33,000</b><i className="green-line" /></div></div><div className="preview-chart"><div className="preview-chart-head"><span>Sales overview</span><b>Last 7 days</b></div><svg viewBox="0 0 330 95" preserveAspectRatio="none" aria-label="Sales trend preview"><defs><linearGradient id="introFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#7667ee" stopOpacity=".3" /><stop offset="1" stopColor="#7667ee" stopOpacity="0" /></linearGradient></defs><path d="M0 78 C25 69 29 73 52 62 S91 66 111 42 S146 50 168 54 S199 28 218 37 S251 18 276 27 S307 11 330 5 V95 H0Z" fill="url(#introFill)" /><path d="M0 78 C25 69 29 73 52 62 S91 66 111 42 S146 50 168 54 S199 28 218 37 S251 18 276 27 S307 11 330 5" fill="none" stroke="#7667ee" strokeWidth="2.5" /></svg><div className="preview-days"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div><div className="preview-bottom"><div><span>Next repayment</span><b>₹4,583</b><small>Due in 7 days</small></div><div className="preview-progress"><span>Loan progress</span><b>55%</b><i><em /></i></div></div></div>
          </div>
          <div className="floating-card floating-card-bottom"><div className="floating-icon purple"><Wallet size={15} /></div><div><small>Loan balance</small><strong>₹25,000</strong></div><span className="mini-badge">On track</span></div>
        </div>
      </section>
      <section className="intro-features"><div className="section-label">EVERYTHING YOU NEED TO STAY ON TOP</div><div className="feature-grid"><div className="intro-feature"><div className="feature-icon purple"><Wallet size={19} /></div><h3>Know your loans</h3><p>See exactly what you borrowed, what you have repaid, and what is still outstanding.</p></div><div className="intro-feature"><div className="feature-icon green"><TrendingUp size={19} /></div><h3>Track daily sales</h3><p>Record income and expenses in seconds, then understand your business trends at a glance.</p></div><div className="intro-feature"><div className="feature-icon orange"><CalendarDays size={19} /></div><h3>Never miss a payment</h3><p>Keep your repayment schedule clear with timely reminders and a simple calendar.</p></div></div></section>
      <section className="intro-sdg"><div className="sdg-mark">8</div><div><div className="section-label">A PROJECT WITH PURPOSE</div><h2>Supporting decent work<br />and economic growth.</h2><p>MicroLoan Tracker is designed to help small vendors organize their everyday financial records and make more informed business decisions.</p></div><button className="intro-text-link" onClick={onEnter}>See how it works <ArrowUpRight size={16} /></button></section>
    </main>
    <footer className="intro-footer"><span>© 2026 MicroLoan Tracker</span><span>Simple financial tracking for small businesses.</span><span>Built for the next step.</span></footer>
  </div>
}

function StatCard({ label, value, meta, tone, icon: Icon }: { label: string; value: string; meta: string; tone: string; icon: typeof Wallet }) { return <div className="stat-card"><div className={cls('stat-icon', tone)}><Icon size={19} /></div><div className="stat-copy"><span>{label}</span><strong>{value}</strong><small>{meta}</small></div></div> }
function Dashboard({ data, onNavigate }: { data: Data; onNavigate: (p: Page) => void }) {
  const totalBorrowed = data.loans.reduce((s, l) => s + l.principal, 0), totalRepaid = data.repayments.reduce((s, r) => s + r.amount, 0), outstanding = data.loans.reduce((s, l) => s + loanOutstanding(l, data.repayments), 0)
  const todaySales = data.sales.filter(s => s.date === iso(today)).reduce((s, x) => s + saleTotal(x), 0)
  const chart = Array.from({ length: 7 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - (6 - i)); const key = iso(d); return { name: d.toLocaleDateString('en-IN', { weekday: 'short' }), amount: data.sales.filter(s => s.date === key).reduce((sum, x) => sum + saleTotal(x), 0) } })
  const active = data.loans.find(l => effectiveLoanStatus(l, data.repayments) !== 'completed')
  return <><div className="stats-grid"><StatCard label="Total borrowed" value={money(totalBorrowed)} meta={`${data.loans.length} loans in total`} tone="purple" icon={Wallet} /><StatCard label="Total repaid" value={money(totalRepaid)} meta={`${totalBorrowed ? Math.round(totalRepaid / data.loans.reduce((s, l) => s + l.total, 0) * 100) : 0}% of total`} tone="green" icon={ArrowUpRight} /><StatCard label="Outstanding balance" value={money(outstanding)} meta={data.loans.filter(l => l.status !== 'completed').length + ' active loans'} tone="orange" icon={CircleDollarSign} /><StatCard label="Today's sales" value={money(todaySales)} meta="Across all categories" tone="blue" icon={TrendingUp} /></div>
    <PlannerSummary data={data} onOpen={() => onNavigate('planner')} />
    <div className="dashboard-grid"><section className="panel chart-panel"><div className="panel-heading"><div><h2>Sales overview</h2><p>Revenue performance over the last 7 days</p></div><button className="select-button">Last 7 days <ChevronRight size={15} /></button></div><div className="chart-legend"><span><i className="dot purple-dot" /> Sales revenue</span><strong>{money(data.sales.filter(s => s.date >= dayOffset(-6)).reduce((sum, sale) => sum + saleTotal(sale), 0))}</strong></div><ResponsiveContainer width="100%" height={238}><AreaChart data={chart}><defs><linearGradient id="salesGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7667ee" stopOpacity=".28" /><stop offset="100%" stopColor="#7667ee" stopOpacity="0" /></linearGradient></defs><CartesianGrid stroke="#edf0f5" vertical={false} /><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#98a1b2', fontSize: 12 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#98a1b2', fontSize: 12 }} tickFormatter={v => `₹${v / 1000}k`} /><Tooltip formatter={(v: number) => [money(v), 'Sales']} contentStyle={{ border: 0, borderRadius: 10, boxShadow: '0 5px 20px #20294320' }} /><Area type="monotone" dataKey="amount" stroke="#7667ee" strokeWidth={2.5} fill="url(#salesGradient)" /></AreaChart></ResponsiveContainer></section>
      <section className="panel progress-panel"><div className="panel-heading"><div><h2>Loan progress</h2><p>Overall repayment status</p></div><button className="icon-btn" onClick={() => onNavigate('loans')}><ChevronRight size={18} /></button></div>{data.loans.length === 0 ? <Empty text="No loans yet." /> : data.loans.slice(0, 3).map(l => <div className="loan-progress" key={l.id}><div className="row-between"><div><strong>{l.loanId}</strong><span>{l.lender}</span></div><b>{loanProgress(l, data.repayments)}%</b></div><div className="progress-track"><div style={{ width: `${loanProgress(l, data.repayments)}%` }} /></div><div className="row-between muted"><span>{money(loanPaid(l, data.repayments))} repaid</span><span>{money(loanOutstanding(l, data.repayments))} left</span></div></div>)}</section></div>
    <div className="lower-grid"><section className="panel"><div className="panel-heading"><div><h2>Upcoming repayment</h2><p>Keep your repayment schedule on track</p></div><button className="text-button" onClick={() => onNavigate('calendar')}>View calendar <ChevronRight size={15} /></button></div>{active ? <div className="upcoming-card"><div className="date-tile"><strong>{new Date(`${active.due}T00:00:00`).getDate()}</strong><span>{new Date(`${active.due}T00:00:00`).toLocaleDateString('en-IN', { month: 'short' })}</span></div><div><strong>{active.lender}</strong><span>{active.loanId} · {active.frequency} repayment</span></div><div className="upcoming-amount"><strong>{money(Math.min(scheduledRepayment(active), loanOutstanding(active, data.repayments)))}</strong><span>Due {dateLabel(active.due)}</span></div></div> : <Empty text="No upcoming repayments." />}</section><section className="panel activity-panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>Your latest financial transactions</p></div><button className="text-button" onClick={() => onNavigate('repayments')}>See all <ChevronRight size={15} /></button></div><div className="activity-list">{[...data.sales.map(s => ({ date: s.date, title: `${s.category} sales`, meta: s.method, amount: saleTotal(s), positive: true })), ...data.repayments.map(r => ({ date: r.date, title: `Repayment · ${data.loans.find(l => l.id === r.loanId)?.loanId ?? ''}`, meta: r.method, amount: r.amount, positive: false }))].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 4).map((x, i) => <div className="activity-item" key={i}><div className={cls('activity-icon', x.positive ? 'sales-icon' : 'repay-icon')}>{x.positive ? <ShoppingBag size={16} /> : <ArrowDownRight size={16} />}</div><div><strong>{x.title}</strong><span>{x.meta} · {dateLabel(x.date)}</span></div><b className={x.positive ? 'positive' : ''}>{x.positive ? '+' : '-'}{money(x.amount)}</b></div>)}</div></section></div></>
}

function plannerMetrics(data: Data, reserve: number, selectedLoanId?: string) {
  const todayRecords = data.sales.filter(s => s.date === iso(today))
  const sales = todayRecords.reduce((sum, sale) => sum + saleTotal(sale), 0)
  const expenses = todayRecords.reduce((sum, sale) => sum + sale.expenses, 0)
  const availableCash = Math.max(0, sales - expenses - reserve)
  const outstanding = data.loans.reduce((sum, loan) => sum + loanOutstanding(loan, data.repayments), 0)
  const availableLoans = data.loans.filter(loan => loanOutstanding(loan, data.repayments) > 0).sort((a, b) => a.due.localeCompare(b.due))
  const upcoming = availableLoans.find(loan => loan.id === selectedLoanId) ?? availableLoans[0]
  const upcomingAmount = upcoming ? Math.min(scheduledRepayment(upcoming), loanOutstanding(upcoming, data.repayments)) : 0
  return { sales, expenses, reserve, availableCash, outstanding, upcoming, upcomingAmount }
}

function PlannerSummary({ data, onOpen }: { data: Data; onOpen: () => void }) {
  const availableLoans = data.loans.filter(loan => loanOutstanding(loan, data.repayments) > 0).sort((a, b) => a.due.localeCompare(b.due))
  const [selectedLoanId, setSelectedLoanId] = useState(availableLoans[0]?.id ?? '')
  const metrics = plannerMetrics(data, 500, selectedLoanId)
  return <section className="planner-summary"><div className="planner-summary-heading"><div className="planner-badge"><Sparkles size={16} /></div><div><h2>Smart Repayment Planner</h2><p>Turn today's recorded cash flow into a clear planning estimate.</p></div><div className="planner-summary-actions"><button className="planner-action secondary" onClick={onOpen}>What If I Pay?</button><button className="planner-action" onClick={onOpen}>Run Stress Test</button><button className="planner-open" onClick={onOpen}>Open planner <ChevronRight size={15} /></button></div></div><div className="planner-summary-loan"><label><span>Today's repayment picture for</span><select value={selectedLoanId} onChange={e => setSelectedLoanId(e.target.value)}>{availableLoans.length ? availableLoans.map(loan => <option key={loan.id} value={loan.id}>{loan.loanId} · {money(loanOutstanding(loan, data.repayments))} outstanding</option>) : <option value="">No ongoing loans</option>}</select></label>{metrics.upcoming && <small>Next due {dateLabel(metrics.upcoming.due)} · Interest rate {metrics.upcoming.interest}%</small>}</div><div className="planner-summary-values"><div><span>Today's sales</span><strong>{money(metrics.sales)}</strong></div><div><span>Today's expenses</span><strong>{money(metrics.expenses)}</strong></div><div><span>Cash reserve</span><strong>{money(metrics.reserve)}</strong></div><div className="allocation-value"><span>Suggested allocation</span><strong>{money(metrics.availableCash)}</strong></div></div><p className="planner-disclaimer">Planning estimate based on your recorded data — not financial advice.</p></section>
}

function SmartPlanner({ data }: { data: Data }) {
  const [reserve, setReserve] = useState('500')
  const [proposed, setProposed] = useState('2000')
  const availableLoans = data.loans.filter(loan => loanOutstanding(loan, data.repayments) > 0).sort((a, b) => a.due.localeCompare(b.due))
  const [selectedLoanId, setSelectedLoanId] = useState(availableLoans[0]?.id ?? '')
  const metrics = plannerMetrics(data, Math.max(0, Number(reserve) || 0), selectedLoanId)
  const payment = Math.max(0, Number(proposed) || 0)
  const selectedLoan = metrics.upcoming
  const selectedOutstanding = selectedLoan ? loanOutstanding(selectedLoan, data.repayments) : metrics.outstanding
  const newOutstanding = Math.max(0, selectedOutstanding - payment)
  const newProgress = selectedLoan ? Math.min(100, Math.round((loanPaid(selectedLoan, data.repayments) + payment) / selectedLoan.total * 100)) : 0
  const stress = [0, 10, 20, 40].map(reduction => {
    const adjustedSales = metrics.sales * (1 - reduction / 100)
    const available = Math.max(0, adjustedSales - metrics.expenses - metrics.reserve)
    return { reduction, sales: adjustedSales, available, difference: available - metrics.upcomingAmount }
  })
  return <div className="planner-page"><div className="planner-intro"><div><div className="eyebrow planner-eyebrow"><Sparkles size={13} /> PLANNING TOOL</div><h2>Make a repayment plan<br /><em>that fits today's numbers.</em></h2><p>Connect your recorded sales, expenses, upcoming repayments, outstanding loans, and a cash reserve in one view.</p></div><div className="planner-note"><CircleDollarSign size={18} /><span><strong>Informational only</strong>Use this to explore scenarios — never as a prediction or financial advice.</span></div></div>
    <div className="planner-layout"><section className="panel planner-calculator"><div className="panel-heading"><div><h2>Today's repayment picture</h2><p>Based on your recorded financial data</p></div><span className="live-pill"><i /> Live</span></div><div className="planner-input"><label className="field"><span>Loan to plan for</span><select value={selectedLoanId} onChange={e => setSelectedLoanId(e.target.value)}>{availableLoans.length ? availableLoans.map(loan => <option key={loan.id} value={loan.id}>{loan.loanId} · {money(loanOutstanding(loan, data.repayments))} outstanding</option>) : <option value="">No ongoing loans</option>}</select></label><label className="field"><span>Cash reserve you want to keep</span><div className="currency-input"><b>₹</b><input type="number" min="0" value={reserve} onChange={e => setReserve(e.target.value)} /></div></label><small>A buffer kept aside before suggesting any allocation.</small></div><div className="planner-breakdown"><div><span>Today's sales</span><strong>{money(metrics.sales)}</strong></div><div className="minus">−</div><div><span>Today's expenses</span><strong>{money(metrics.expenses)}</strong></div><div className="minus">−</div><div><span>Cash reserve</span><strong>{money(metrics.reserve)}</strong></div><div className="equals">=</div><div className="suggested-box"><span>Suggested allocation</span><strong>{money(metrics.availableCash)}</strong></div></div><div className="planner-upcoming"><CalendarDays size={17} /><div><span>Selected loan repayment</span><strong>{metrics.upcoming ? `${metrics.upcoming.loanId} · ${money(metrics.upcomingAmount)}` : 'No ongoing loan recorded'}</strong>{metrics.upcoming && <small>Interest rate {metrics.upcoming.interest}% · Recorded interest {money(loanInterestAmount(metrics.upcoming))}</small>}</div>{metrics.upcoming && <small>Due {dateLabel(metrics.upcoming.due)}</small>}</div><p className="planner-disclaimer">Planning estimate based on your recorded data — not financial advice.</p></section>
      <section className="panel what-if-card"><div className="panel-heading"><div><h2>What if I pay?</h2><p>Simulate a proposed repayment</p></div><div className="simulator-icon"><SlidersHorizontal size={16} /></div></div><label className="field"><span>Proposed repayment amount</span><div className="currency-input"><b>₹</b><input type="number" min="0" value={proposed} onChange={e => setProposed(e.target.value)} /></div></label><div className="what-if-results"><div><span>Current outstanding</span><strong>{money(selectedOutstanding)}</strong></div><div><span>New outstanding</span><strong>{money(newOutstanding)}</strong></div><div><span>New repayment progress</span><strong>{newProgress}%</strong></div><div><span>Cash remaining today</span><strong className={payment > metrics.availableCash ? 'negative' : 'positive'}>{money(metrics.availableCash - payment)}</strong></div></div><div className={cls('cash-message', payment > metrics.availableCash ? 'warning-message' : 'ok-message')}>{payment > metrics.availableCash ? '⚠️ This payment is higher than your recorded available cash today.' : '✓ Within your recorded cash flow.'}</div><p className="planner-disclaimer">Simulation only. It does not predict repayment outcomes.</p></section></div>
    <section className="panel stress-panel"><div className="panel-heading"><div><h2>Repayment stress test</h2><p>Explore how lower recorded sales could change today's planning estimate.</p></div><span className="test-label"><Activity size={15} /> Scenario view</span></div><div className="stress-chart"><ResponsiveContainer width="100%" height={215}><BarChart data={stress} barCategoryGap="25%"><CartesianGrid stroke="#edf0f5" vertical={false} /><XAxis dataKey="reduction" tickFormatter={v => v === 0 ? 'Normal' : `-${v}%`} axisLine={false} tickLine={false} tick={{ fill: '#8993a5', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#8993a5', fontSize: 10 }} tickFormatter={v => `₹${v / 1000}k`} /><Tooltip formatter={(v: number) => [money(v), 'Available after reserve']} contentStyle={{ border: 0, borderRadius: 9 }} /><Bar dataKey="available" radius={[5, 5, 0, 0]}>{stress.map((entry, index) => <Cell key={entry.reduction} fill={index === 0 ? '#7667ee' : '#b9b3f7'} />)}</Bar></BarChart></ResponsiveContainer></div><div className="stress-table"><div className="stress-row stress-head"><span>Scenario</span><span>Adjusted sales</span><span>Available after reserve</span><span>Compared with next repayment</span></div>{stress.map(scenario => <div className="stress-row" key={scenario.reduction}><strong>{scenario.reduction === 0 ? 'Normal sales' : `${scenario.reduction}% lower sales`}</strong><span>{money(scenario.sales)}</span><span>{money(scenario.available)}</span><span className={scenario.difference >= 0 ? 'positive' : 'negative'}>{scenario.difference >= 0 ? 'Within recorded cash flow' : 'Above recorded cash flow'}</span></div>)}</div><p className="planner-disclaimer">Stress test scenarios are simulations based on recorded numbers. They do not predict default or whether you will be able to repay.</p></section>
  </div>
}

function recordedDailyMetrics(data: Data) {
  const days = new Set(data.sales.map(s => s.date))
  const sales = data.sales.reduce((sum, sale) => sum + saleTotal(sale), 0)
  const expenses = data.sales.reduce((sum, sale) => sum + sale.expenses, 0)
  const dayCount = Math.max(1, days.size)
  return { salesPerDay: sales / dayCount, expensesPerDay: expenses / dayCount, netPerDay: (sales - expenses) / dayCount }
}

function ReverseLoanPlanner({ data }: { data: Data }) {
  const loans = data.loans.filter(loan => loanOutstanding(loan, data.repayments) > 0)
  const [loanId, setLoanId] = useState(loans[0]?.id ?? '')
  const [months, setMonths] = useState('4')
  const [earlyPayment, setEarlyPayment] = useState(() => loans[0] ? String(Math.round(loanOutstanding(loans[0], data.repayments))) : '')
  const loan = loans.find(item => item.id === loanId) ?? loans[0]
  useEffect(() => { setEarlyPayment(loan ? String(Math.round(loanOutstanding(loan, data.repayments))) : '') }, [loan?.id])
  const targetMonths = Math.max(1, Number(months) || 1)
  const outstanding = loan ? loanOutstanding(loan, data.repayments) : 0
  const daily = outstanding / (targetMonths * 30)
  const weekly = daily * 7
  const monthly = outstanding / targetMonths
  const historicalNet = recordedDailyMetrics(data).netPerDay
  const percentage = historicalNet > 0 ? daily / historicalNet * 100 : 0
  const interest = loan ? loanInterestAmount(loan) : 0
  const remainingLoanInterest = loan ? remainingInterest(loan, data.repayments) : 0
  const earlyPaymentAmount = Math.min(outstanding, Math.max(0, Number(earlyPayment) || 0))
  const estimatedInterestSaved = outstanding > 0 ? remainingLoanInterest * earlyPaymentAmount / outstanding : 0
  return <div className="feature-page"><div className="feature-hero reverse-hero"><div><div className="eyebrow feature-eyebrow"><TrendingUp size={13} /> WORK BACKWARDS FROM A GOAL</div><h2>Set a target.<br /><em>See the maths.</em></h2><p>Explore hypothetical repayment amounts for a target timeline and compare them with your recorded historical cash flow.</p></div><div className="simulation-label"><CalendarDays size={17} /><strong>Mathematical planning tool</strong><span>It does not say whether you can afford a payment.</span></div></div><div className="feature-grid-2"><section className="panel control-panel"><div className="panel-heading"><div><h2>Reverse loan planner</h2><p>Choose a balance and target</p></div></div><label className="field"><span>Loan</span><select value={loan?.id ?? ''} onChange={e => setLoanId(e.target.value)}>{loans.map(item => <option key={item.id} value={item.id}>{item.loanId} · {money(loanOutstanding(item, data.repayments))} outstanding</option>)}</select></label><Field label="Finish loan in (months)" value={months} onChange={setMonths} type="number" /><div className="goal-balance"><span>Current outstanding loan</span><strong>{money(outstanding)}</strong>{loan && <small>Interest rate {loan.interest}% · Recorded interest {money(interest)}</small>}</div><label className="field"><span>Hypothetical early payment</span><div className="currency-input"><b>₹</b><input type="number" min="0" max={outstanding} value={earlyPayment} placeholder={String(Math.round(outstanding))} onChange={e => setEarlyPayment(e.target.value)} /></div></label></section><section className="panel reverse-results"><div className="panel-heading"><div><h2>Hypothetical repayment target</h2><p>{targetMonths} months · assumes 30 days per month</p></div></div><div className="repayment-target-grid"><div><span>Daily hypothetical repayment</span><strong>{money(daily)}</strong></div><div><span>Weekly hypothetical repayment</span><strong>{money(weekly)}</strong></div><div><span>Monthly hypothetical repayment</span><strong>{money(monthly)}</strong></div></div><div className="historical-compare"><Activity size={17} /><div><span>Historical average daily net cash flow</span><strong>{money(historicalNet)}</strong><p>Based on your recorded sales and expenses, the required daily repayment represents <b>{historicalNet > 0 ? `${Math.round(percentage)}%` : 'N/A'}</b> of average daily net cash flow.</p></div></div><div className="historical-compare"><Wallet size={17} /><div><span>Estimated interest saved by paying early</span><strong>{money(estimatedInterestSaved)}</strong><p>Based on the recorded flat-interest model and the hypothetical early payment of {money(earlyPaymentAmount)}.</p></div></div></section></div><p className="feature-disclaimer">Hypothetical calculations only — based on your existing loan balance and historical records. Early-payment savings are an estimate under the recorded flat-interest model, not a lender quote or financial advice.</p></div>
}

function RepaymentDNA({ data }: { data: Data }) {
  const amounts = data.repayments.map(item => item.amount).sort((a, b) => a - b)
  const average = data.repayments.length ? data.repayments.reduce((sum, item) => sum + item.amount, 0) / data.repayments.length : 0
  const median = amounts.length ? amounts.length % 2 ? amounts[Math.floor(amounts.length / 2)] : (amounts[amounts.length / 2 - 1] + amounts[amounts.length / 2]) / 2 : 0
  const intervals = data.repayments.slice().sort((a, b) => a.date.localeCompare(b.date)).slice(1).map((item, index) => Math.max(0, Math.round((new Date(`${item.date}T00:00:00`).getTime() - new Date(`${data.repayments.slice().sort((a, b) => a.date.localeCompare(b.date))[index].date}T00:00:00`).getTime()) / 86400000)))
  const averageInterval = intervals.length ? intervals.reduce((sum, value) => sum + value, 0) / intervals.length : 0
  const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  const dayCounts = data.repayments.reduce<Record<string, number>>((counts, item) => { const day = days[new Date(`${item.date}T00:00:00`).getDay()]; counts[day] = (counts[day] || 0) + 1; return counts }, {})
  const commonDay = Object.entries(dayCounts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? 'Not enough data'
  const beforeMetrics = (repayment: Repayment) => { const end = new Date(`${repayment.date}T00:00:00`).getTime(); const records = data.sales.filter(sale => { const time = new Date(`${sale.date}T00:00:00`).getTime(); return time < end && time >= end - 7 * 86400000 }); return { sales: records.reduce((sum, sale) => sum + saleTotal(sale), 0), net: records.reduce((sum, sale) => sum + saleTotal(sale) - sale.expenses, 0) } }
  const prior = data.repayments.map(beforeMetrics)
  const averageBeforeSales = prior.length ? prior.reduce((sum, item) => sum + item.sales, 0) / prior.length : 0
  const averageBeforeNet = prior.length ? prior.reduce((sum, item) => sum + item.net, 0) / prior.length : 0
  const frequency = averageInterval ? `Every ${Math.round(averageInterval)} days` : data.repayments.length ? 'Based on first record' : 'No history yet'
  const DNAStat = ({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) => <div className="dna-stat"><div className="dna-stat-icon">{icon}</div><span>{label}</span><strong>{value}</strong></div>
  return <div className="feature-page"><div className="feature-hero dna-hero"><div><div className="eyebrow feature-eyebrow"><CircleDollarSign size={13} /> YOUR HISTORICAL PATTERN</div><h2>Your repayment<br /><em>DNA.</em></h2><p>Understand the patterns in your recorded repayment history. This describes what has happened — it does not score or predict you.</p></div><div className="simulation-label"><ClipboardList size={17} /><strong>Pattern profile</strong><span>Only historical repayments and recorded cash flow are used.</span></div></div>{data.repayments.length ? <><div className="dna-grid"><DNAStat label="Typical repayment" value={money(average)} icon={<ArrowUpRight size={16} />} /><DNAStat label="Median repayment" value={money(median)} icon={<BarChart3 size={16} />} /><DNAStat label="Largest repayment" value={money(Math.max(...amounts))} icon={<TrendingUp size={16} />} /><DNAStat label="Smallest repayment" value={money(Math.min(...amounts))} icon={<ArrowDownRight size={16} />} /></div><div className="feature-grid-2"><section className="panel dna-panel"><div className="panel-heading"><div><h2>Repayment rhythm</h2><p>Timing patterns in your records</p></div><span className="sim-badge">{data.repayments.length} records</span></div><div className="dna-lines"><div><span>Average interval</span><strong>{averageInterval ? `${Math.round(averageInterval)} days` : 'Not enough data'}</strong></div><div><span>Most common repayment day</span><strong>{commonDay}</strong></div><div><span>Repayment frequency</span><strong>{frequency}</strong></div></div></section><section className="panel dna-panel"><div className="panel-heading"><div><h2>Cash flow before repayment</h2><p>Seven recorded days before each payment</p></div></div><div className="dna-lines"><div><span>Average sales before repayment</span><strong>{money(averageBeforeSales)}</strong></div><div><span>Average net cash flow before repayment</span><strong>{money(averageBeforeNet)}</strong></div><div><span>Pattern basis</span><strong>Recorded data only</strong></div></div></section></div></> : <section className="panel"><Empty text="No repayment history yet." /></section>}<p className="feature-disclaimer">Repayment DNA only describes patterns found in your historical data. It is not a credit score, creditworthiness assessment, prediction, or financial advice.</p></div>
}

function Empty({ text }: { text: string }) { return <div className="empty"><Sparkles size={21} /><strong>{text}</strong><span>Records you add will appear here.</span></div> }
function PageToolbar({ action, onAction, placeholder = 'Search...' }: { action: string; onAction: () => void; placeholder?: string }) { return <div className="page-toolbar"><div className="filter-search"><Search size={17} /><input placeholder={placeholder} /></div><button className="button button-primary" onClick={onAction}><Plus size={17} /> {action}</button></div> }
function Status({ status }: { status: string }) { return <span className={cls('status', status.toLowerCase())}><i />{status[0].toUpperCase() + status.slice(1)}</span> }
function Loans({ data, setModal, search }: { data: Data; setModal: (m: 'loan' | 'repayment' | 'sale' | null) => void; search: string }) { const loans = data.loans.filter(l => !search || `${l.loanId} ${l.lender}`.toLowerCase().includes(search.toLowerCase())); return <><PageToolbar action="Add loan" onAction={() => setModal('loan')} placeholder="Search loans..." /><section className="panel table-panel"><div className="panel-heading"><div><h2>Loan portfolio</h2><p>{loans.length} loans · values are calculated from your records</p></div><button className="filter-button"><SlidersHorizontal size={16} /> Filter</button></div>{loans.length ? <div className="table-wrap"><table><thead><tr><th>Loan</th><th>Principal</th><th>Repaid</th><th>Outstanding</th><th>Next due</th><th>Status</th><th>Progress</th></tr></thead><tbody>{loans.map(l => <tr key={l.id}><td><strong>{l.loanId}</strong><small>{l.lender}</small></td><td>{money(l.principal)}</td><td>{money(loanPaid(l, data.repayments))}</td><td><strong>{money(loanOutstanding(l, data.repayments))}</strong></td><td>{dateLabel(l.due)}</td><td><Status status={effectiveLoanStatus(l, data.repayments)} /></td><td><div className="mini-progress"><div style={{ width: `${loanProgress(l, data.repayments)}%` }} /></div><small>{loanProgress(l, data.repayments)}%</small></td></tr>)}</tbody></table></div> : <Empty text="No loans yet. Add your first loan to start tracking repayments." />}</section></> }
function Repayments({ data, setModal }: { data: Data; setModal: (m: 'loan' | 'repayment' | 'sale' | null) => void }) { return <><PageToolbar action="Record repayment" onAction={() => setModal('repayment')} /><section className="panel table-panel"><div className="panel-heading"><div><h2>Repayment history</h2><p>All payments made towards your loans</p></div></div>{data.repayments.length ? <div className="table-wrap"><table><thead><tr><th>Date</th><th>Loan</th><th>Amount</th><th>Payment method</th><th>Reference</th><th>Status</th></tr></thead><tbody>{[...data.repayments].sort((a, b) => b.date.localeCompare(a.date)).map(r => <tr key={r.id}><td>{dateLabel(r.date)}</td><td><strong>{data.loans.find(l => l.id === r.loanId)?.loanId ?? 'Unknown'}</strong></td><td><strong>{money(r.amount)}</strong></td><td>{r.method}</td><td className="muted">{r.reference || '—'}</td><td><span className="status completed"><i />Successful</span></td></tr>)}</tbody></table></div> : <Empty text="No repayments recorded yet." />}</section></> }
function Sales({ data, setModal }: { data: Data; setModal: (m: 'loan' | 'repayment' | 'sale' | null) => void }) { const total = data.sales.reduce((s, x) => s + saleTotal(x), 0), expenses = data.sales.reduce((s, x) => s + x.expenses, 0); return <><PageToolbar action="Record sale" onAction={() => setModal('sale')} /><div className="stats-grid compact"><StatCard label="Total sales" value={money(total)} meta={`${data.sales.length} records`} tone="purple" icon={TrendingUp} /><StatCard label="Total expenses" value={money(expenses)} meta="Recorded expenses" tone="orange" icon={ArrowDownRight} /><StatCard label="Estimated net" value={money(total - expenses)} meta="Sales less expenses" tone="green" icon={Activity} /><StatCard label="Average daily sales" value={money(data.sales.length ? total / Math.max(1, new Set(data.sales.map(s => s.date)).size) : 0)} meta="Based on records" tone="blue" icon={BarChart3} /></div><section className="panel table-panel"><div className="panel-heading"><div><h2>Sales records</h2><p>Sales amount is per customer; gross sales = amount × customers</p></div><button className="filter-button"><SlidersHorizontal size={16} /> Date filter</button></div>{data.sales.length ? <div className="table-wrap"><table><thead><tr><th>Date</th><th>Category</th><th>Per-customer sale</th><th>Customers</th><th>Gross sales</th><th>Payment method</th><th>Expenses</th><th>Net amount</th></tr></thead><tbody>{data.sales.sort((a, b) => b.date.localeCompare(a.date)).map(s => <tr key={s.id}><td>{dateLabel(s.date)}</td><td><strong>{s.category}</strong></td><td>{money(s.amount)}</td><td>{s.customers}</td><td><strong>{money(saleTotal(s))}</strong></td><td>{s.method}</td><td>{money(s.expenses)}</td><td><strong className="positive">{money(saleTotal(s) - s.expenses)}</strong></td></tr>)}</tbody></table></div> : <Empty text="No sales recorded yet." />}</section></> }
function Calendar({ data }: { data: Data }) { const entries = data.loans.filter(l => effectiveLoanStatus(l, data.repayments) !== 'completed').map(l => ({ ...l, amount: Math.min(scheduledRepayment(l), loanOutstanding(l, data.repayments)), effectiveStatus: effectiveLoanStatus(l, data.repayments) })).sort((a, b) => a.due.localeCompare(b.due)); return <section className="panel calendar-panel"><div className="panel-heading"><div><h2>Repayment calendar</h2><p>Stay ahead of your upcoming payments</p></div><div className="calendar-filters"><button className="active">All</button><button>Upcoming</button><button>Overdue</button></div></div>{entries.length ? <div className="schedule-list">{entries.map(l => <div className="schedule-row" key={l.id}><div className="date-tile"><strong>{new Date(`${l.due}T00:00:00`).getDate()}</strong><span>{new Date(`${l.due}T00:00:00`).toLocaleDateString('en-IN', { month: 'short' })}</span></div><div className="schedule-main"><strong>{l.loanId} · {l.lender}</strong><span>{l.frequency} repayment · {dateLabel(l.due)}</span></div><div><strong>{money(l.amount)}</strong><Status status={l.effectiveStatus === 'overdue' ? 'overdue' : 'upcoming'} /></div><ChevronRight size={18} className="muted" /></div>)}</div> : <Empty text="No upcoming repayments." />}</section> }
function Reports({ data }: { data: Data }) { const sales = data.sales.reduce((sum, sale) => sum + saleTotal(sale), 0), expenses = data.sales.reduce((s, x) => s + x.expenses, 0), borrowed = data.loans.reduce((s, x) => s + x.principal, 0), repaid = data.repayments.reduce((s, x) => s + x.amount, 0); return <><div className="report-actions"><button className="button button-secondary"><Download size={16} /> Export CSV</button><button className="select-button">Last 30 days <ChevronRight size={15} /></button></div><div className="report-grid"><section className="panel report-card"><div className="report-title"><div className="report-icon purple"><BarChart3 size={19} /></div><div><h2>Sales report</h2><p>Gross sales = per-customer amount × customers</p></div></div><div className="report-lines"><div><span>Total sales</span><strong>{money(sales)}</strong></div><div><span>Total expenses</span><strong>{money(expenses)}</strong></div><div><span>Estimated net</span><strong className="positive">{money(sales - expenses)}</strong></div></div></section><section className="panel report-card"><div className="report-title"><div className="report-icon green"><Wallet size={19} /></div><div><h2>Loan report</h2><p>Borrowing at a glance</p></div></div><div className="report-lines"><div><span>Total borrowed</span><strong>{money(borrowed)}</strong></div><div><span>Total repaid</span><strong>{money(repaid)}</strong></div><div><span>Outstanding</span><strong>{money(data.loans.reduce((s, l) => s + loanOutstanding(l, data.repayments), 0))}</strong></div></div></section><section className="panel report-card"><div className="report-title"><div className="report-icon orange"><CalendarDays size={19} /></div><div><h2>Repayment report</h2><p>Schedule health</p></div></div><div className="report-lines"><div><span>Number of repayments</span><strong>{data.repayments.length}</strong></div><div><span>Upcoming payments</span><strong>{data.loans.filter(l => l.status === 'active').length}</strong></div><div><span>Overdue payments</span><strong>{data.loans.filter(l => l.status === 'overdue').length}</strong></div></div></section></div></> }
function Notifications({ data, updateData }: { data: Data; updateData: (d: Data) => void }) { return <section className="panel notifications-panel"><div className="panel-heading"><div><h2>Notifications</h2><p>Stay informed about your business activity</p></div><button className="text-button" onClick={() => updateData({ ...data, notifications: data.notifications.map(n => ({ ...n, read: true })) })}>Mark all as read</button></div>{data.notifications.length ? data.notifications.map(n => <div className={cls('notification-row', !n.read && 'unread')} key={n.id}><div className={cls('notification-icon', n.type)}>{n.type === 'warning' ? <CircleDollarSign size={17} /> : n.type === 'success' ? <Check size={17} /> : <Bell size={17} />}</div><div><strong>{n.title}</strong><p>{n.message}</p><small>{dateLabel(n.date)}</small></div>{!n.read && <span className="unread-dot" />}</div>) : <Empty text="You're all caught up." />}</section> }
function Profile({ profile, setProfile }: { profile: typeof demoData extends never ? never : { name: string; business: string; type: string; phone: string; email: string; location: string }; setProfile: (p: { name: string; business: string; type: string; phone: string; email: string; location: string }) => void }) { const [draft, setDraft] = useState(profile); return <div className="profile-grid"><section className="panel profile-card"><div className="profile-avatar">RS</div><h2>{profile.name}</h2><p>{profile.business}</p><span className="role-pill">Vendor account</span><div className="about-project"><Sparkles size={17} /><div><strong>About MicroLoan Tracker</strong><p>Helping small vendors organize loans, repayments, sales and everyday financial records. Aligned conceptually with UN Sustainable Development Goal 8: Decent Work and Economic Growth.</p></div></div></section><section className="panel form-panel"><div className="panel-heading"><div><h2>Profile details</h2><p>Keep your business information up to date</p></div></div><div className="form-grid"><Field label="Full name" value={draft.name} onChange={v => setDraft({ ...draft, name: v })} /><Field label="Business name" value={draft.business} onChange={v => setDraft({ ...draft, business: v })} /><Field label="Business type" value={draft.type} onChange={v => setDraft({ ...draft, type: v })} /><Field label="Phone" value={draft.phone} onChange={v => setDraft({ ...draft, phone: v })} /><Field label="Email" value={draft.email} onChange={v => setDraft({ ...draft, email: v })} /><Field label="Location" value={draft.location} onChange={v => setDraft({ ...draft, location: v })} /></div><button className="button button-primary save-profile" onClick={() => { setProfile(draft); alert('Profile saved') }}>Save changes</button></section></div> }
function Admin({ data }: { data: Data }) { return <><div className="stats-grid"><StatCard label="Total vendors" value="1" meta="Demo workspace" tone="purple" icon={Store} /><StatCard label="Total borrowed" value={money(data.loans.reduce((s, l) => s + l.principal, 0))} meta={`${data.loans.length} loans`} tone="blue" icon={Wallet} /><StatCard label="Total sales" value={money(data.sales.reduce((sum, sale) => sum + saleTotal(sale), 0))} meta="All vendors" tone="green" icon={TrendingUp} /><StatCard label="Outstanding" value={money(data.loans.reduce((s, l) => s + loanOutstanding(l, data.repayments), 0))} meta="Across portfolio" tone="orange" icon={CircleDollarSign} /></div><section className="panel table-panel"><div className="panel-heading"><div><h2>Vendor directory</h2><p>Authorized vendor data only</p></div><div className="filter-search"><Search size={16} /><input placeholder="Search vendors..." /></div></div><div className="vendor-row"><div className="avatar">RS</div><div><strong>Rahul Sharma</strong><span>Rahul Fresh Fruits · Pune</span></div><Status status="active" /><ChevronRight size={18} /></div></section></> }

function Field({ label, value, onChange, type = 'text', required = true, readOnly = false }: { label: string; value: string | number; onChange: (v: string) => void; type?: string; required?: boolean; readOnly?: boolean }) { return <label className="field"><span>{label}{required && <em>*</em>}</span><input required={required} readOnly={readOnly} type={type} value={value} onChange={e => onChange(e.target.value)} /></label> }
function Modal({ title, subtitle, close, children }: { title: string; subtitle: string; close: () => void; children: React.ReactNode }) { return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={close}><X size={19} /></button><div className="modal-heading"><h2>{title}</h2><p>{subtitle}</p></div>{children}</div></div> }
function LoanModal({ close, save }: { close: () => void; save: (item: Loan) => void }) {
  const [form, setForm] = useState({ loanId: '', lender: '', principal: '', interest: '0', start: iso(today), due: dayOffset(30), frequency: 'Monthly', duration: '12', notes: '' })
  const update = (key: string, value: string) => setForm({ ...form, [key]: value })
  const principal = Number(form.principal) || 0
  const interestRate = Number(form.interest) || 0
  const interestAmount = principal * interestRate / 100
  const total = principal + interestAmount
  const submit = (e: React.FormEvent) => {
    e.preventDefault()
    if (principal <= 0 || interestRate < 0 || Number(form.duration) <= 0 || !form.start || !form.due) return
    save({ id: crypto.randomUUID(), loanId: form.loanId || `LN-${Date.now().toString().slice(-4)}`, lender: form.lender, principal, interest: interestRate, total, start: form.start, due: form.due, frequency: form.frequency, duration: Number(form.duration), status: 'active', notes: form.notes })
  }
  return <Modal title="Add a new loan" subtitle="Interest and total repayment are calculated automatically from the principal." close={close}><form onSubmit={submit}><div className="form-grid">
    <Field label="Loan ID" value={form.loanId} onChange={v => update('loanId', v)} required={false} />
    <Field label="Lender name" value={form.lender} onChange={v => update('lender', v)} />
    <Field label="Principal amount" value={form.principal} onChange={v => update('principal', v)} type="number" />
    <Field label="Interest rate (%)" value={form.interest} onChange={v => update('interest', v)} type="number" />
    <Field label="Interest amount" value={interestAmount.toFixed(2)} onChange={() => undefined} readOnly />
    <Field label="Total repayment amount" value={total.toFixed(2)} onChange={() => undefined} readOnly />
    <Field label="Duration (months)" value={form.duration} onChange={v => update('duration', v)} type="number" />
    <Field label="Start date" value={form.start} onChange={v => update('start', v)} type="date" />
    <Field label="First due date" value={form.due} onChange={v => update('due', v)} type="date" />
  </div><label className="field"><span>Repayment frequency</span><select value={form.frequency} onChange={e => update('frequency', e.target.value)}><option>Daily</option><option>Weekly</option><option>Monthly</option></select></label><label className="field"><span>Notes</span><textarea value={form.notes} onChange={e => update('notes', e.target.value)} /></label><div className="modal-actions"><button type="button" className="button button-secondary" onClick={close}>Cancel</button><button className="button button-primary">Add loan</button></div></form></Modal>
}
function RepaymentModal({ data, close, save }: { data: Data; close: () => void; save: (item: Repayment) => void }) { const [form, setForm] = useState({ loanId: data.loans[0]?.id ?? '', amount: '', date: iso(today), method: 'UPI' as PaymentMethod, reference: '', notes: '' }); const submit = (e: React.FormEvent) => { e.preventDefault(); const loan = data.loans.find(l => l.id === form.loanId), amount = Number(form.amount); if (!loan || effectiveLoanStatus(loan, data.repayments) === 'completed' || amount <= 0 || amount > loanOutstanding(loan, data.repayments) || !form.date) return; save({ ...form, id: crypto.randomUUID(), amount }) }; return <Modal title="Record a repayment" subtitle="Log a payment against one of your active loans." close={close}><form onSubmit={submit}><label className="field"><span>Loan<em>*</em></span><select value={form.loanId} onChange={e => setForm({ ...form, loanId: e.target.value })}>{data.loans.filter(l => effectiveLoanStatus(l, data.repayments) !== 'completed').map(l => <option key={l.id} value={l.id}>{l.loanId} · {money(loanOutstanding(l, data.repayments))} outstanding</option>)}</select></label><div className="form-grid"><Field label="Amount" value={form.amount} onChange={v => setForm({ ...form, amount: v })} type="number" /><Field label="Payment date" value={form.date} onChange={v => setForm({ ...form, date: v })} type="date" /><Field label="Reference ID" value={form.reference} onChange={v => setForm({ ...form, reference: v })} required={false} /></div><label className="field"><span>Payment method</span><select value={form.method} onChange={e => setForm({ ...form, method: e.target.value as PaymentMethod })}>{['Cash', 'UPI', 'Bank Transfer', 'Other'].map(x => <option key={x}>{x}</option>)}</select></label><div className="modal-actions"><button type="button" className="button button-secondary" onClick={close}>Cancel</button><button className="button button-primary">Save repayment</button></div></form></Modal> }
function SaleModal({ close, save }: { close: () => void; save: (item: Sale) => void }) { const [form, setForm] = useState({ date: iso(today), category: 'Fruits', amount: '', customers: '', method: 'UPI' as PaymentMethod, expenses: '0', notes: '' }); const submit = (e: React.FormEvent) => { e.preventDefault(); const amount = Number(form.amount), customers = Number(form.customers), expenses = Number(form.expenses); if (amount <= 0 || customers <= 0 || expenses < 0 || !form.date || !form.category.trim()) return; save({ ...form, id: crypto.randomUUID(), amount, expenses, customers }) }; return <Modal title="Record a sale" subtitle="Enter the sale amount per customer. Gross sales are calculated as amount × customers, then expenses are deducted." close={close}><form onSubmit={submit}><div className="form-grid"><Field label="Date" value={form.date} onChange={v => setForm({ ...form, date: v })} type="date" /><Field label="Category" value={form.category} onChange={v => setForm({ ...form, category: v })} /><Field label="Amount per customer" value={form.amount} onChange={v => setForm({ ...form, amount: v })} type="number" /><Field label="Number of customers" value={form.customers} onChange={v => setForm({ ...form, customers: v })} type="number" /><Field label="Expenses" value={form.expenses} onChange={v => setForm({ ...form, expenses: v })} type="number" /></div><label className="field"><span>Payment method</span><select value={form.method} onChange={e => setForm({ ...form, method: e.target.value as PaymentMethod })}>{['Cash', 'UPI', 'Card', 'Bank Transfer', 'Other'].map(x => <option key={x}>{x}</option>)}</select></label><label className="field"><span>Notes</span><textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></label><div className="modal-actions"><button type="button" className="button button-secondary" onClick={close}>Cancel</button><button className="button button-primary">Record sale</button></div></form></Modal> }
